name: Build EXE

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Verify logo.ico exists
      run: |
        if (Test-Path "logo.ico") {
          Write-Host "logo.ico found"
          Get-ChildItem "logo.ico"
        } else {
          Write-Host "Warning: logo.ico not found"
        }
      shell: pwsh
      
    - name: Build EXE
      run: |
        python build_exe.py
      shell: pwsh
      
    - name: List dist directory
      run: |
        if (Test-Path "dist") {
          Write-Host "Contents of dist directory:"
          Get-ChildItem "dist" -Recurse
        } else {
          Write-Host "dist directory not found"
        }
      shell: pwsh
      
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: 按键小精灵-exe
        path: |
          dist/按键小精灵.exe
          dist/*.png
          dist/*.json
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/按键小精灵.exe
          dist/*.png
          dist/*.json
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
